[tool.ruff]
# Increase line length to 100 characters
line-length = 100

# Exclude directories
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    ".pytest_cache",
    "allure-results",
    "temp",
]

# Target Python versions
target-version = "py312"

[tool.ruff.lint]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "N",  # pep8-naming
    "UP", # pyupgrade
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
]

# Ignore specific rules
ignore = [
    "E501",  # line too long (handled by line-length)
]

[tool.ruff.format]
# Like Black formatter
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
# isort configuration
known-first-party = ["clients", "tools", "fixtures", "tests"]
